### ISSUE TITLE
Need to export types

### ISSUE THREAD

**Issue by hosseinmd** [syntax-tree/mdast-util-from-markdown#16]
### Subject of the feature

In typescript project we need to use type, this module not exported types

### Expected behavior

Export Types, at least `Root` and `Content`

### Alternatives

What are the alternative solutions?  Please describe what else you have considered?

**Comment by ChristianMurphy** [comment]
The types are exported
https://github.com/syntax-tree/mdast-util-from-markdown/blob/f0f2280f3d4966431208931e3ae02f524566d845/package.json#L35
https://github.com/syntax-tree/mdast-util-from-markdown/blob/f0f2280f3d4966431208931e3ae02f524566d845/types/index.d.ts#L1-L34

> Root and Content

These types are available as a part of `@types/mdast`, they aren't specific to `mdast-util-from-markdown` package, and I don't think it makes sense for this pacakge to export them.
You can use them by installing types mdast, then

```ts
import type {Root, Content} from 'mdast'
```
