### ISSUE TITLE
Markdown start with code

### ISSUE THREAD

**Issue by hosseinmd** [syntax-tree/mdast-util-from-markdown#18]
### Subject of the issue
Markdown starting with code, code recognizing as text
For example
```
\`\`\`js
var a = 0;
\`\`\
```
When add a new line to the beginning of text that will work well.
### Your environment

*   **OS**: Mac 
*   **Packages**: 
*   **Env**: node 14

**Comment by wooorm** [comment]
Can you try explaining your question again?

You can use more ticks around code in markdown:

`````markdown
````markdown
```js
asdasd
```
````
`````

**Comment by hosseinmd** [comment]
I have a Markdown which starting with code block, but this library parse it as code.

**Comment by wooorm** [comment]
I don't understand, can you try again, and probably use my tip above to show what you have?

**Comment by hosseinmd** [comment]
I found that the code block need to begin with '\n````' but when starting with '```' can't parse.

**Comment by wooorm** [comment]
I don’t understand what you’re asking. See here for more on how markdown works: https://commonmark.org/help/, this link for trying out how it works: https://spec.commonmark.org/dingus/, and see this for how to ask questions: https://github.com/syntax-tree/.github/blob/main/support.md.

**Comment by hosseinmd** [comment]
My English is bad I can't explain good, Excuse me, please look this code https://github.com/hosseinmd/prettier-plugin-jsdoc/blob/455bc292ccc3fab88a447db51fd9ecd2edcb6013/src/descriptionFormatter.ts#L87

**Comment by wooorm** [comment]
It works fine: https://runkit.com/embed/tsva83dlhiys
