### ISSUE TITLE
return prefix size of Indented code in gfm 

### ISSUE THREAD

**Issue by TimWei** [syntax-tree/mdast-util-from-markdown#19]
### Subject of the feature
return prefix size of Indented code in gfm 

### Problem
Currently there is no way to know that code blocks were generating from ``` or indented.
While we are trying to add some custom text linting in code block, and found that might causing some problem if we need to calculating the column position of text.

For example we'll get same column position of below both two code syntax:

````
# heading
```
code
```
````

````
# heading
    code
````

If in second syntax, there is anyway to get the length of line prefix.  or any flag to know that code block was indented. It'll make calculating correct column position easier.

### Expected behavior

````
    code
````
will return something like `linePrefix: 4` in position object while parsing code that Indented.

### Alternatives

currently we patch how `micromark` [handling codeIndented](https://github.com/micromark/micromark/blob/5a90585c1ba8414f05888329265440c1aa112311/lib/tokenize/code-indented.mjs) to adding line prefix length into codeIndented token then get it in [compiler](https://github.com/syntax-tree/mdast-util-from-markdown/blob/main/lib/index.js#L482).

**Comment by wooorm** [comment]
That is information that doesn’t belong in an AST, similar to how it doesn’t matter if a string was double or single quoted. It’s an *abstract* syntax tree.

What do you want to lint and why?

**Comment by TimWei** [comment]
We are developing a markdown editor let user sharing IP information, and lint it while user inputing a invalid IP address.
It might be like:
````
    1.1.1.1
    2.2.2.
````
we want to lint the invalid ones and found that it might be a problem while user inputs with code block.

**Comment by wooorm** [comment]
I don’t see why, in this case, you’d need to differentiate between indented and fenced code?

**Comment by TimWei** [comment]
we lint text by calculating its offset and length from ast. so if both of two syntax returns exactly same result of ast that will make us linting at exactly same position for both. the linting will be on code block prefix indents instead of text.

**Comment by wooorm** [comment]
Could you please expand on this with for example input/output, and code? I don’t understand.

**Comment by TimWei** [comment]
for example, 
````javascript
ast = require('mdast-util-from-markdown')('```\nip: 1.1.1\n```')
````
will resulting ast like 
````javascript
{ type: 'root',
  children:
   [ { type: 'code',
       lang: null,
       meta: null,
       value: 'ip: 1.1.1',
       position:    
        { start: { line: 1, column: 1, offset: 0 },
          end: { line: 3, column: 4, offset: 17 } } } ],
  position:
   { start: { line: 1, column: 1, offset: 0 },
     end: { line: 3, column: 4, offset: 17 } } }
````

then we can indexing  `1.1.1` starts at 4 offset from code ast value. plus its length 5. we will linting column 4 to 8.

but it encounter with indented code:
````javascript
require('mdast-util-from-markdown')('    ip: 1.1.1\n')
````
it still generating ast like

````javascript
{ type: 'root',
  children:
   [ { type: 'code',
       lang: null,
       meta: null,
       value: 'ip: 1.1.1',
       position: { start: { line: 1, column: 1, offset: 0 },
                         end: { line: 1, column: 14, offset: 13 } } } ],
  position:
   { start: { line: 1, column: 1, offset: 0 },
     end: { line: 2, column: 1, offset: 14 } } }
````

since idents were ignored in value. so we still calculating linting position about column 5 to 8 like fenced one while column 0~3 are indents.

**Comment by wooorm** [comment]
Thanks for clarifying. The code you post is working as expected from the perspective of this project.

For solutions to your problem, here are some ideas:

a) put the location of the warnings you want to show at the code level, perhaps that’s specific enough
b) detect the style of a code block with `/^[ ]{0,3}([~`])\1{2,}/`: if this regex matches `doc.slice(code.position.start.offset, code.position.start.offset + 6)`, it’s fenced code
c) search for the substring you want to warn about in `doc.slice(code.position.start.offset, code.position.end.offset)` to infer the location

**Comment by TimWei** [comment]
we currently work around is to adding linePrefix(which should be first token of cold) token length into code ast. and thinking that it might be a useful information to anyone who need to locating code text position. 

but yeah. this is over perspective of what ast should do. 

thanks for your quick reply and time. really appreciate it.
