### ISSUE TITLE
Footnote as paragraph 

### ISSUE THREAD

**Issue by crystalfp** [syntax-tree/mdast-util-from-markdown#2]
### Subject of the issue

Sometimes a footnote is parsed as `definition` and sometimes as `paragraph`

### Your environment

*   **OS**: Windows 10 64 bits
*   **Packages**: "mdast-util-from-markdown": "^0.5.0" and "@types/node": "^14.11.1"
*   **Env**: node: 14.8.0 npm: 6.14.7

### Steps to reproduce
Parse the following text:
```
*Il relatore del Convegno[^1] è il professore Franco Cambi. La ragione per cui il CEM[^2] ha invitato il Prof. Cambi.*

[^1]: ***42° Convegno Nazionale Cem Mondialità*** PER UN'EDUCAZIONE CAPACE DI FUTURO Viterbo 23-28 agosto 2003

[^2]: <http://www.saveriani.bs.it/cem/Convegno/Conv42/atti.html>
```
The code to call the parser:
```
import fs from "fs";
import fromMarkdown from "mdast-util-from-markdown";

const doc = fs.readFileSync(process.argv[2], "utf-8");

const tree: fromMarkdown.Tree = fromMarkdown(doc);
console.log(JSON.stringify(tree, undefined, 2));
```
[Sidenote: I have added types to satisfy the typescript compiler. I'm not yet satisfied, but could be a starting point.]

### Expected behavior
The two footnotes parsed in the same way (`definition` or whatever), with the footnote content accessed as its children. This is how a header is parser btw.

### Actual behavior

The first footnote is parsed as `paragraph` making difficult to extract all footnotes of a text.

**Comment by crystalfp** [comment]
Forgot to mention that in the text the first reference `[^1]` is parsed as nothing special inside a `text` block, the second one `[^2]` as ` linkReference`.

**Comment by wooorm** [comment]
Footnotes do not exist in markdown (commonmark or gfm), so they will be in an extension. Soon!

**Comment by wooorm** [comment]
appendix a) I would suggest using remark with remark-footnotes for now. Or wait a couple days
appendix b) you’re pretty fast at this project, so a warning that the dust hasn’t settled, and also: welcome! do let us know of bugs!

**Comment by crystalfp** [comment]
I understand. I was just so happy to have found an alternative to my home-made partial parser...

Maybe, the only important thing is consistency, that is to have both footnotes parsed the same.

**Comment by crystalfp** [comment]
Maybe this will be useful during your extension development.
A footnote could contain multiple paragraphs, like for example in <https://pandoc.org/MANUAL.html#footnotes>
Currently the subsequent paragraphs are parsed as `code`. An example from the mentioned page:
```
Here is a footnote reference,[^1] and another.[^longnote]

[^1]: Here is the footnote.

[^longnote]: Here's one with multiple blocks.

    Subsequent paragraphs are indented to show that they
belong to the previous footnote.

        { some.code }

    The whole paragraph can be indented, or just the first
    line.  In this way, multi-paragraph footnotes work like
    multi-paragraph list items.

This paragraph won't be part of the note, because it
isn't indented.
```

**Comment by wooorm** [comment]
Those are currently supported in remark and remark footnotes, which also output mdast. And they will work in the new extension!

**Comment by wooorm** [comment]
Closed w/ https://github.com/syntax-tree/mdast-util-footnote.

**Comment by crystalfp** [comment]
The extension works perfectly. Thanks!

**Comment by wooorm** [comment]
Great to hear!

Footnotes are not specified anywhere, so I tried to do what makes the most sense for CommonMark (which is different from Pandoc). So, your mileage may vary based on what markdown parser you used before — hope this syntax makes sense!

**Comment by crystalfp** [comment]
From an initial test the interpretation seems OK. The only thing that is not clear is the difference between `identifier` and `label` in `footnoteReference` block. Maybe it is documented in mdast.
Thanks again!

**Comment by wooorm** [comment]
Depends on what you want to use! Typically they’re equivalent, although `label` includes casing and understands character escapes and -references.

Unfortunately though, `[&amp;]` and `[&]` or `[\&]` don’t match according to CommonMark. For the matching to work, the original source must be used, and then normalized, which is available in `identifier`.

See also https://github.com/syntax-tree/mdast/issues/35.
