### ISSUE TITLE
`mdast-util-from-markdown/types` not found

### ISSUE THREAD

**Issue by ivodolenc** [syntax-tree/mdast-util-from-markdown#20]
Hi, I don’t know if this is a bug, but I've been getting these notifications in several projects lately:

**jsconfig.json**

```
File '/Users/.../node_modules/mdast-util-from-markdown/types' not found. ts [1,1]
File '/Users/.../node_modules/mdast-util-from-markdown/types' not found. ts [1,1]
File '/Users/.../node_modules/mdast-util-from-markdown/types' not found. ts [1,1]
File '/Users/.../node_modules/mdast-util-from-markdown/types' not found. ts [1,1]
```

I'm not sure, maybe it's a problem with `VScode` because I was also getting similar error messages for the `dotenv` package.

To remove these error messages, I need to open the `vscode` settings (`./vscode/settings.json`), change some option and save it. After that the messages disappear but reappear after a while.

Please let me know if you need more info. Thanks for your time.

**Comment by wooorm** [comment]
Can you go into your node_modules to see if changing the value of this line:

https://github.com/syntax-tree/mdast-util-from-markdown/blob/f0f2280f3d4966431208931e3ae02f524566d845/package.json#L35

To `types/index.d.ts` solves it?

**Comment by ivodolenc** [comment]
Thanks for fast reply. 

I changed the code according to your instructions (`"types": "types/index.d.ts"`) but the error messages did not disappear.

But when I add this code to `jsconfig.json`:

```json
  "typeAcquisition": {
    "exclude": ["dotenv", "mdast-util-from-markdown"]
  }
```

messages for `mdast-util-from-markdown` disappear immediately, but then the same messages for` mdast-util-to-markdown` appear.

```
File '/Users/.../node_modules/mdast-util-to-markdown/types' not found. ts [1,1]
File '/Users/.../node_modules/mdast-util-to-markdown/types' not found. ts [1,1]
File '/Users/.../node_modules/mdast-util-to-markdown/types' not found. ts [1,1]
```

**Comment by ChristianMurphy** [comment]
You mention you are using `jsconfig.json`, what is your configuration?
in particular are `modules` and `moduleResolution` setup to find node modules?
https://code.visualstudio.com/docs/languages/jsconfig#_jsconfig-options

**Comment by ivodolenc** [comment]
For example, here is the [`boilerplate`](https://github.com/ivodolenc/nuxt-static-boilerplate) I use for some projects where these warning messages appear.

- [vscode/settings.json](https://github.com/ivodolenc/nuxt-static-boilerplate/blob/master/.vscode/settings.json)
- [jsconfig.json](https://github.com/ivodolenc/nuxt-static-boilerplate/blob/master/jsconfig.json)

Don't get me wrong, everything works as expected, I didn't notice that it interferes with the project.

Notifications appear on the `Problems` tab, in the same window as the `Terminal`, so they are a bit annoying.

**Comment by ChristianMurphy** [comment]
Again, you may want to try setting `module` and `moduleResolution` https://code.visualstudio.com/docs/languages/jsconfig#_jsconfig-options
It sounds like the issue has less to do with dotenv or mdast-util-from-markdown, and more to do with VSCode not knowing where to look for the typings.

Anecdotally, I've used both packages with TypeScript and VSCode, with `module` set to `commonJS` and `moduleResolution` set to `node` and the typings load as expected.

**Comment by ivodolenc** [comment]
Thanks for suggestion, but that didn't solve this, messages are still there.

**Comment by ChristianMurphy** [comment]
Some additional suggestions, try changing _jsconfig.json_ to _tsconfig.json_ with `allowJS` set to `true` https://www.typescriptlang.org/tsconfig#allowJs.

If the issue still persists, the vscode community may have more insights on how to tune your vscode config https://stackoverflow.com/questions/tagged/visual-studio-code
It looks like this question has come up several times around vue + ts + vscode projects https://stackoverflow.com/search?q=%5Bvisual-studio-code%5D+not+found.+ts&s=70bfdfb7-50fb-49ec-be36-639387ae68e5 the answer may already be on a thread.

**Comment by ivodolenc** [comment]
Ok I understand, again thanks for your time and help.
