### ISSUE TITLE
`Cannot read property 'write' of undefined` when parsing some lists

### ISSUE THREAD

**Issue by mathieudutour** [syntax-tree/mdast-util-from-markdown#27]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

1.0.4

### Link to runnable example

https://codesandbox.io/s/remark-debug-forked-38j17

### Steps to reproduce

Try to parse
```
* a
  * * b
  * * c
```

### Expected behavior

Does not throw an error

### Actual behavior

Throws `Cannot read property 'write' of undefined`

### Runtime

Node v16

### Package manager

npm v7

### OS

macOS

### Build and bundle tools

Webpack

**Comment by wooorm** [comment]
I think it was solved in https://github.com/micromark/micromark/releases/tag/3.0.4
