### ISSUE TITLE
Feature Request: export internal function for extension developer

### ISSUE THREAD

**Issue by ylc395** [syntax-tree/mdast-util-from-markdown#35]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Some internal functions like `enter` / `exit` can be reused by developers when developing extensions. Shall we export them? I have to copy and paste them in my codebase for my own extension now.

### Solution

export them

### Alternatives

none

**Comment by wooorm** [comment]
They are exposed through `this`; I don’t think you ned to copy/paste them.
I also made ±10 extensions, which don’t need that. So I doubt you need to copy/paste them.
If you do, please explain or show your code for why

**Comment by ylc395** [comment]
They are exported in context. Sorry for my rash issue 🙏
