### ISSUE TITLE
Backslashes are incorrectly removed

### ISSUE THREAD

**Issue by hosseinmd** [syntax-tree/mdast-util-from-markdown#36]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.0.0 || 1.X

### Steps to reproduce

original issue https://github.com/hosseinmd/prettier-plugin-jsdoc/issues/152

```
\\\\ 
```

### Expected behavior

return a paragraph with `\\\\`

### Actual behavior

return `\\`

### Affected runtime and version

node@18.2

### Build and bundle tools

Rollup

**Comment by wooorm** [comment]
I doubt it. Please make a reproducible example with this project.

**Comment by wooorm** [comment]
Feel free to post a repro, thanks
