### ISSUE TITLE
Shorthand link references not recognized when there's whitespace between []

### ISSUE THREAD

**Issue by nzakas** [syntax-tree/mdast-util-from-markdown#39]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-from-markdown@2.0.1

### Link to runnable example

https://stackblitz.com/edit/stackblitz-starters-ifpvft?file=index.js

### Steps to reproduce

1. Create a link reference with whitespace in between the `[]`:

```markdown
[foo][ ]

[foo]: https://example.com
```

2. Pass into `fromMarkdown()`

### Expected behavior

The returned AST should identify `[foo][ ]` as a `linkReference`. (It appears that GitHub does this. I'm unsure if that's standard behavior for Markdown or not. The Micromark GFM extension exhibits the same behavior.)

### Actual behavior

The returned AST identifies `[foo][ ]` as `text` rather than a link reference.

### Affected runtime and version

node@20.13.0

**Comment by ChristianMurphy** [comment]
Hey @nzakas! 👋 
Commonmark specifies that spaces are significant and it would not match
https://spec.commonmark.org/dingus/?text=%5Bfoo%5D%5B%20%5D%0A%0A%5Bfoo%5D%3A%20https%3A%2F%2Fexample.com

I don't see any spec changes in https://github.github.com/gfm/#link-reference-definitions to reference links
This may be a bug in https://github.com/github/cmark-gfm

**Comment by wooorm** [comment]
This seems to be https://github.com/commonmark/commonmark-spec/issues/653, which shows that most tools work differently than the spec.

I think the spec is currently saying that this is *not* allowed:

* what you post *could* be a shortcut reference, but then it would leave the `[ ]` in the resulting HTML, which is also not what you expected
* what you post *cannot* be a collapsed reference, “followed by the string `[]`”, which this is not

I do consider this to be something that can improved in CM.

But I also consider this a current bug in GFM, which says it sticks to CM, so I don’t feel good about “solving” it in `micromark-extension-gfm`.

**Comment by nzakas** [comment]
To make sure I'm following, it sounds like you're saying that the spec disallows this behavior, so this is a bug in GitHub's Markdown parser?

**Comment by wooorm** [comment]
Correct

**Comment by fasttime** [comment]
I think that in this example, spaces and line breaks are not significant:

```markdown
[foo][
  bar ]

[bar
]: https://example.com
```

https://spec.commonmark.org/dingus/?text=%5Bfoo%5D%5B%20%5D%0A%0A%5Bfoo%5D%3A%20https%3A%2F%2Fexample.com

But they are significant if there are only spacing characters?

**Comment by wooorm** [comment]
Correct. There’s indeed a “gap” between the different shortcut links and how they are defined in CM. Shortcut (`[x]`), collapsed (`[x][]`), vs. full (`[x][y]`). Making nzakas’s  case ambiguous/vague/weird.
