### ISSUE TITLE
Support nested code blocks and blockquotes in lists

### ISSUE THREAD

**Issue by weiQuill** [syntax-tree/mdast-util-from-markdown#40]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Problem

Hi team,
Is it possible to support such structural conversion?
```
1. milk
	> banana
2. cheese
```

Expect
```
[
	{
		type: "list",
		children: [
			{ type: "list item", ... },
			{ type: "blockquote", ... },
			{ type: "list item", ... },
		]
 	}
]
```

Actual
```
[
	{
		type: "list",
		children: [
			{ type: "list item", ... },
		]
 	},
	{ type: "blockquote", ... },
	{
		type: "list",
		children: [
			{ type: "list item", ... },
		]
 	}
]
```

### The markdown works fine in GitHub
1. milk
	> banana
2. cheese
-------------------
1. milk
	```
	banana
	```
2. cheese
-------------------
### Solution

None

### Alternatives

None

**Comment by wooorm** [comment]
What you want is not possible, and it is not needed.

Lists have list items. On GH too. You cannot remove the list items. And you do not need to.

The block quote is *inside* the item. On GH too.

```js
import {fromMarkdown} from 'mdast-util-from-markdown'
import {removePosition} from 'unist-util-remove-position'

const document = `1. milk
	> banana
2. cheese`
const tree = fromMarkdown(document)
removePosition(tree, {force: true})

console.dir(tree, {depth: null})
```

```js
{
  type: 'root',
  children: [
    {
      type: 'list',
      ordered: true,
      start: 1,
      spread: false,
      children: [
        {
          type: 'listItem',
          spread: false,
          checked: null,
          children: [
            {
              type: 'paragraph',
              children: [ { type: 'text', value: 'milk' } ]
            },
            {
              type: 'blockquote',
              children: [
                {
                  type: 'paragraph',
                  children: [ { type: 'text', value: 'banana' } ]
                }
              ]
            }
          ]
        },
        {
          type: 'listItem',
          spread: false,
          checked: null,
          children: [
            {
              type: 'paragraph',
              children: [ { type: 'text', value: 'cheese' } ]
            }
          ]
        }
      ]
    }
  ]
}
```

**Comment by weiQuill** [comment]
Thanks you @wooorm , that works for me!
I am using `mdast-util-from-markdown 2.0.0`, and called `fromMarkdown` like this:
```
const tree: Parent = fromMarkdown(text, {
	extensions: [gfmStrikethrough(), gfmTable(), gfmTaskListItem()],
	mdastExtensions: [gfmTableFromMarkdown(), gfmStrikethroughFromMarkdown(), gfmTaskListItemFromMarkdown()],
}) as Parent;
```
But got the tree different from yours:
```
tree {
	type: 'root',
	children: [
		{
			type: 'list',
			ordered: true,
			start: 1,
			spread: false,
			children: [Array],
			position: [Object]
		},
		{ type: 'blockquote', children: [Array], position: [Object] },
		{
			type: 'list',
			ordered: true,
			start: 2,
			spread: false,
			children: [Array],
			position: [Object]
		}
	],
	position: {
        start: { line: 1, column: 1, offset: 0 },
        end: { line: 4, column: 1, offset: 29 }
	}
}
```
Do you know how this happened? Huge thanks!

**Comment by wooorm** [comment]
Can you show the actual code and versions? I am quite sure `text` is different from what you post here

**Comment by wooorm** [comment]
And make your reproduction smaller: remove everything that is not needed. Remove every extension that’s not needed.

**Comment by weiQuill** [comment]
weird, If I pass in the string you used directly, I can get the same result as yours. If I read the markdown from another md file, I will get the incorrect result.
[10-quote-in-list.md](https://github.com/user-attachments/files/17843945/10-quote-in-list.md)

**Comment by wooorm** [comment]
It’s not weird, it’s well specified. It’s the difference between 2 spaces and a tab. In markdown, that tab there is worth 4 spaces.

You do not use enough spaces.
Take this: the block quote is not in the list item.

```markdown
1. milk
> banana
```

Same with this, 1 is not enough:

```markdown
1. milk
 > banana
```

Same, 2 is not enough:

```markdown
1. milk
  > banana
```

Because `1` and `.` and ` ` are 3, you need 3 spaces:

```markdown
1. milk
   > banana
```

**Comment by weiQuill** [comment]
Thank you very much! It works now:)
